server:
  port: 8081
  session:
    tracking-modes: cookie

okta:
  client:
    orgUrl: https://dev-468567.oktapreview.com
  oauth2:
    redirectUri: /authorization-code/callback
    issuer: https://dev-468567.oktapreview.com/oauth2/default
    clientSecret: FJ3gkGUoItBWGJifX9z0-2dmQZlPtBjxO7lAr1_h
    clientId: 0oah3p2nj4lDcp9kx0h7

security:
  oauth2:
    client:
      # Redirect to your local page and render the widget
      userAuthorizationUri: http://localhost:${server.port}/login
      scope: openid profile email